name: 'RPM Build'
description: 'Builds RPM from spec file'

inputs:
  spec_file:
    description: 'path to the spec file'
    required: true

outputs:
  source_rpm_path:
    description: 'path to Source RPM file'
  source_rpm_dir_path:
    description: 'path to  SRPMS directory'
  source_rpm_name:
    description: 'name of Source RPM file'
  rpm_dir_path:
    description: 'path to RPMS directory'
  rpm_content_type:
    description: 'Content-type for Upload'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'red'

