#!/bin/bash

set -ex

rpmbuild -bb --build-in-place --target=x86_64 \
  --define="_rpmfilename %%{NAME}-%%{VERSION}.%%{ARCH}.rpm" \
  --define="version $VERSION" \
  --define "_rpmdir $OUT_DIR" \
  "$SPEC_FILE"
