#!/bin/bash

set -ex

dnf builddep -y --spec "$SPEC_FILE"

rpmbuild -bb --build-in-place --target=x86_64 \
  --define="_rpmfilename %%{NAME}-%%{VERSION}.%%{ARCH}.rpm" \
  --define="version $VERSION" \
  --define "_rpmdir $OUT_DIR" \
  "$SPEC_FILE"

RPM_PATH=`rpmspec --builtrpms --target=x86_64 \
  --define="version $VERSION" \
   -q --qf "$OUT_DIR/%{name}-%{version}.%{arch}.rpm" \
  "$SPEC_FILE"`

echo "::set-output name=rpm_path::$RPM_PATH"
