name: test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: rpm
        with:
          spec_file: ./test/test.spec
          version: v1.0.0
          out_dir: ./release
      - run: echo ${{ steps.rpm.outputs.rpm_path }}
