name: test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  rpm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          spec_file: ./test/test.spec
